{
  "hooks":
    {
      "before:init": ["git fetch --tags"],
      "after:bump": "npx auto-changelog -p",
    },
  "git":
    {
      "requireBranch": "main",
      "requireCleanWorkingDir": true,
      "requireUpstream": true,
      "commitMessage": "chore: release ${version}",
      "tagName": "v${version}",
      "tagAnnotation": "Release v${version}",
    },
  "github": { "release": true, "releaseName": "Release ${version}" },
}
