// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/5/2025, 6:54:10 PM
const configMerger = require("/Users/nico/Documents/Projet/portfolio/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.2_magicast@0.3.5_rollup@4.27.2/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/nico/Documents/Projet/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nico/Documents/Projet/portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nico/Documents/Projet/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nico/Documents/Projet/portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nico/Documents/Projet/portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nico/Documents/Projet/portfolio/plugins/**/*.{js,ts,mjs}","/Users/nico/Documents/Projet/portfolio/composables/**/*.{js,ts,mjs}","/Users/nico/Documents/Projet/portfolio/utils/**/*.{js,ts,mjs}","/Users/nico/Documents/Projet/portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/nico/Documents/Projet/portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/nico/Documents/Projet/portfolio/app.config.{js,ts,mjs}"] } }));

module.exports = config
